import React, { useState } from 'react';
import { Button } from '../ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Badge } from '../ui/badge';
import { useData } from '../../contexts/DataContext';
import { ReportPreview } from './ReportPreview';
import { Download, FileText, Calendar, Filter, Loader2 } from 'lucide-react';

export function Reports() {
  const { wetlands, generateReport } = useData();
  const [selectedWetland, setSelectedWetland] = useState('');
  const [startDate, setStartDate] = useState(() => {
    const date = new Date();
    date.setDate(date.getDate() - 30);
    return date.toISOString().split('T')[0];
  });
  const [endDate, setEndDate] = useState(() => {
    return new Date().toISOString().split('T')[0];
  });
  const [reportData, setReportData] = useState<any>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const handleGenerateReport = async () => {
    if (!selectedWetland) return;

    setIsGenerating(true);
    try {
      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      const data = generateReport(selectedWetland, {
        start: startDate + 'T00:00:00Z',
        end: endDate + 'T23:59:59Z'
      });
      setReportData(data);
    } catch (error) {
      console.error('Error generating report:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadPDF = async () => {
    if (!reportData) return;

    setIsDownloading(true);
    try {
      // Simulate PDF generation delay
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // In a real application, you would generate and download the actual PDF
      // For this demo, we'll create a simple text representation
      const content = generatePDFContent(reportData);
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${reportData.wetland.name}_Report_${startDate}_to_${endDate}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading report:', error);
    } finally {
      setIsDownloading(false);
    }
  };

  const handleDownloadCSV = async () => {
    if (!reportData) return;

    setIsDownloading(true);
    try {
      // Simulate CSV generation delay
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      const csvContent = generateCSVContent(reportData);
      const blob = new Blob([csvContent], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${reportData.wetland.name}_Data_${startDate}_to_${endDate}.csv`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading CSV:', error);
    } finally {
      setIsDownloading(false);
    }
  };

  const generatePDFContent = (data: any) => {
    return `
KA-ECO WETLAND MONITORING REPORT
================================

Wetland: ${data.wetland.name}
Location: ${data.wetland.location.lat}, ${data.wetland.location.lng}
Area: ${data.wetland.area} hectares
Type: ${data.wetland.type}
Status: ${data.wetland.status}

Report Period: ${startDate} to ${endDate}
Generated: ${new Date().toLocaleString()}

SUMMARY
=======
Total Readings: ${data.summary.totalReadings}
Critical Alerts: ${data.summary.criticalAlerts}
Warning Alerts: ${data.summary.warningAlerts}
Average Temperature: ${data.summary.avgTemperature.toFixed(1)}°C
Average pH: ${data.summary.avgPH.toFixed(1)}

DESCRIPTION
===========
${data.wetland.description}

SENSOR DATA
===========
${data.readings.map((reading: any) => `
${new Date(reading.timestamp).toLocaleString()} - ${reading.sensorType}: ${reading.value} ${reading.unit} (${reading.status})
`).join('')}

---
Generated by Ka-Eco Urban Wetlands Monitoring System
`;
  };

  const generateCSVContent = (data: any) => {
    const headers = 'Timestamp,Sensor Type,Value,Unit,Status,Wetland ID,Wetland Name\n';
    const rows = data.readings.map((reading: any) => 
      `${reading.timestamp},${reading.sensorType},${reading.value},${reading.unit},${reading.status},${reading.wetlandId},${data.wetland.name}`
    ).join('\n');
    return headers + rows;
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1>Reports & Analytics</h1>
        <p className="text-muted-foreground">
          Generate comprehensive reports on wetland environmental data
        </p>
      </div>

      {/* Report Generation Form */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Generate Report
          </CardTitle>
          <CardDescription>
            Select a wetland and date range to generate a detailed environmental report
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="wetland">Wetland</Label>
              <Select value={selectedWetland} onValueChange={setSelectedWetland}>
                <SelectTrigger>
                  <SelectValue placeholder="Select wetland" />
                </SelectTrigger>
                <SelectContent>
                  {wetlands.map(wetland => (
                    <SelectItem key={wetland.id} value={wetland.id}>
                      {wetland.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="startDate">Start Date</Label>
              <Input
                id="startDate"
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="endDate">End Date</Label>
              <Input
                id="endDate"
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                max={new Date().toISOString().split('T')[0]}
              />
            </div>
          </div>

          <Button 
            onClick={handleGenerateReport} 
            disabled={!selectedWetland || isGenerating}
            className="w-full md:w-auto"
          >
            {isGenerating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating Report...
              </>
            ) : (
              <>
                <Filter className="mr-2 h-4 w-4" />
                Generate Report
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Report Preview and Download */}
      {reportData && (
        <>
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Report Preview</CardTitle>
                  <CardDescription>
                    {reportData.wetland.name} • {startDate} to {endDate}
                  </CardDescription>
                </div>
                <div className="flex gap-2">
                  <Button 
                    variant="outline" 
                    onClick={handleDownloadCSV}
                    disabled={isDownloading}
                  >
                    {isDownloading ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                      <Download className="mr-2 h-4 w-4" />
                    )}
                    CSV
                  </Button>
                  <Button 
                    onClick={handleDownloadPDF}
                    disabled={isDownloading}
                  >
                    {isDownloading ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                      <Download className="mr-2 h-4 w-4" />
                    )}
                    PDF Report
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <ReportPreview reportData={reportData} />
            </CardContent>
          </Card>
        </>
      )}

      {/* Quick Stats */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">Available Reports</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {wetlands.map(wetland => (
                <div key={wetland.id} className="flex items-center justify-between text-sm">
                  <span>{wetland.name}</span>
                  <Badge variant="secondary" className="text-xs">
                    {wetland.sensors.length} sensors
                  </Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">Data Coverage</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span>Total Wetlands:</span>
                <span className="font-medium">{wetlands.length}</span>
              </div>
              <div className="flex justify-between">
                <span>Healthy Sites:</span>
                <span className="font-medium text-green-600">
                  {wetlands.filter(w => w.status === 'healthy').length}
                </span>
              </div>
              <div className="flex justify-between">
                <span>Critical Sites:</span>
                <span className="font-medium text-red-600">
                  {wetlands.filter(w => w.status === 'critical').length}
                </span>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">Report Features</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2 text-sm">
              <div className="flex items-center gap-2">
                <Calendar className="h-3 w-3" />
                Custom date ranges
              </div>
              <div className="flex items-center gap-2">
                <Download className="h-3 w-3" />
                PDF & CSV exports
              </div>
              <div className="flex items-center gap-2">
                <FileText className="h-3 w-3" />
                Detailed analytics
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}